### PR TITLE
feat: add conformance test for content-* fields

### PR DESCRIPTION
**Pull request by frankyn**
fixes: https://github.com/googleapis/conformance-tests/issues/36

### CODE REVIEW

**Review by tritone — APPROVED** [review]
Thanks for adding this!

I guess we merge this here and then update all the repos manually?

**Comment by frankyn** [comment]
Pending review from @houglum

**Comment by quartzmo** [comment]
Just FYI, I copied this change into google-cloud-ruby and get the following failures. Hopefully they look correct:

```
# Running:

test_signer_v4_10: POST Policy With Additional Metadata:
policyOutput

expectedDecodedPolicy:

{"conditions":[{"content-disposition":"attachment"},{"content-encoding":"gzip"},{"content-type":"text/plain"},{"success_action_redirect":"http://www.google.com/"},{"bucket":"rsaposttest-1579902671-6ldm6caw4se52vrx"},{"key":"test-object"},{"x-goog-date":"20200123T043530Z"},{"x-goog-credential":"test-iam-credentials@dummy-project-id.iam.gserviceaccount.com/20200123/auto/storage/goog4_request"},{"x-goog-algorithm":"GOOG4-RSA-SHA256"}],"expiration":"2020-01-23T04:35:40Z"}

test_bucket_10: POST Policy With Additional Metadata:
policyOutput

expectedDecodedPolicy:

{"conditions":[{"content-disposition":"attachment"},{"content-encoding":"gzip"},{"content-type":"text/plain"},{"success_action_redirect":"http://www.google.com/"},{"bucket":"rsaposttest-1579902671-6ldm6caw4se52vrx"},{"key":"test-object"},{"x-goog-date":"20200123T043530Z"},{"x-goog-credential":"test-iam-credentials@dummy-project-id.iam.gserviceaccount.com/20200123/auto/storage/goog4_request"},{"x-goog-algorithm":"GOOG4-RSA-SHA256"}],"expiration":"2020-01-23T04:35:40Z"}

Finished in 1.073564s, 857.8902 runs/s, 2496.3579 assertions/s.

  1) Failure:
PostObjectConformanceTest#test_signer_v4_10: POST Policy With Additional Metadata [/Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-storage/test/google/cloud/storage/file/signer_v4/post_object_conformance_test.rb:54]:
--- expected
+++ actual
@@ -1 +1 @@
-["key", "policy", "success_action_redirect", "x-goog-algorithm", "x-goog-credential", "x-goog-date", "x-goog-signature"]
+["content-disposition", "content-encoding", "content-type", "key", "policy", "success_action_redirect", "x-goog-algorithm", "x-goog-credential", "x-goog-date", "x-goog-signature"]


  2) Failure:
PostObjectConformanceTest#test_bucket_10: POST Policy With Additional Metadata [/Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-storage/test/google/cloud/storage/file/signer_v4/post_object_conformance_test.rb:91]:
--- expected
+++ actual
@@ -1 +1 @@
-["key", "policy", "success_action_redirect", "x-goog-algorithm", "x-goog-credential", "x-goog-date", "x-goog-signature"]
+["content-disposition", "content-encoding", "content-type", "key", "policy", "success_action_redirect", "x-goog-algorithm", "x-goog-credential", "x-goog-date", "x-goog-signature"]
```

**Comment by frankyn** [comment]
Thanks @quartzmo, could you take a look at the updated version?

**Comment by quartzmo** [comment]
@frankyn The tests pass now after your latest commit.

**Review by houglum — APPROVED** [review]

**Pull request merged**
