### PR TITLE
fix: add bucket to expected fields

### PR DESCRIPTION
**Pull request by dopiera**
Given that `bucket` is now an obligatory field of the policy, it should
also be obligatory in the fields submitted to GCS.

### CODE REVIEW

**Comment by quartzmo** [comment]
@frankyn Should I hold off on merging googleapis/google-cloud-ruby#5803, which ensures that  `bucket` is not returned in PostObject fields?

**Comment by frankyn** [comment]
You should be okay to merge, but you can't cut a release until Monday.

**Comment by quartzmo** [comment]
@frankyn I'm confused. googleapis/google-cloud-ruby#5803 conflicts with the change in this PR.

**Comment by frankyn** [comment]
Too many PRs and got confused with the context of the PR. Sorry folks.

@manish-qlogic in this case, bucket is not expected in the fields set because the context is provided by the URI. This is expected by the GCS team through conversation: @ranylee and @houglum

**Comment by amanda-tarafa** [comment]
For what is worth I tested today several generated forms and the upload works without the bucket field. According to the docs, the bucket, even when in the policy, can be specified in the post URL or as part of the key when actually posting.
https://cloud.google.com/storage/docs/xml-api/post-object

**Comment by dopiera** [comment]
ACK, sorry for the confusion.

**Comment by frankyn** [comment]
Not a problem, thanks for making sure conformance tests are consistent and sending changes here

**Pull request closed without merging**
