### PR TITLE
move storage/v1/ to storage/

### PR DESCRIPTION
**Pull request by jadekler**

### CODE REVIEW

**Comment by frankyn** [comment]
Need to update Kokoro as well if not it will fail. I followed v1 as an example from @jskeet. Removing v1 is okay with me.

**Comment by jadekler** [comment]
> Need to update Kokoro as well if not it will fail. I followed v1 as an example from @jskeet. Removing v1 is okay with me.

Done

**Comment by frankyn** [comment]
Documentation you just merged in PR#3 will need to be updated with the correct paths with this change.

**Comment by jskeet** [comment]
I would strongly prefer *not* to do this. I think it's worth establishing a precedent of conformance being attached to a particular API version, early on.
If there's a Storage V2 API at some point, half of the conformance tests at that point may well not apply.

It's even more important for proto-based APIs, where often the conformance tests would want to import the API protos. I think it keeps things much cleaner if it's separated by version.

**Comment by frankyn** [comment]
How about xml_v1/ instead of v1/? V4 signatures depend on the XML API.

**Comment by jadekler** [comment]
> Documentation you just merged in PR#3 will need to be updated with the correct paths with this change.

Done

**Comment by jadekler** [comment]
> I would strongly prefer _not_ to do this. I think it's worth establishing a precedent of conformance being attached to a particular API version, early on.
> If there's a Storage V2 API at some point, half of the conformance tests at that point may well not apply.
> 
> It's even more important for proto-based APIs, where often the conformance tests would want to import the API protos. I think it keeps things much cleaner if it's separated by version.

Ack, I don't have strong feelings about this so I'll opt to close the PR. FWIW in Go we don't consider any of the manuals v1, we just have "stable" and "unstable", so I probably see less of this than y'all do. Makes sense, though!

**Pull request closed without merging**
